# Generated by Django 3.1.5 on 2021-09-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Value', models.IntegerField(max_length=30)),
            ],
        ),
    ]
