# Generated by Django 3.1.5 on 2021-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Value',
            field=models.IntegerField(),
        ),
    ]
