# Generated by Django 3.1.5 on 2021-09-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0002_auto_20210909_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='End_Date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Start_Date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Value',
            new_name='value',
        ),
    ]
